# Generated by Django 3.0.7 on 2020-06-28 16:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("mileage", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                (
                    "station",
                    models.ManyToManyField(related_name="work", to="education.Station"),
                ),
            ],
        ),
    ]
