# Generated by Django 3.0.5 on 2020-04-23 19:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_responsibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("name", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="responsibility", name="project",),
        migrations.RenameModel(old_name="Technology", new_name="Degree",),
        migrations.DeleteModel(name="Project",),
        migrations.DeleteModel(name="Responsibility",),
        migrations.AddField(
            model_name="skills",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="education.Degree",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.ManyToManyField(
                related_name="education", to="education.Degree"
            ),
        ),
    ]
