# Generated by Django 3.0.7 on 2020-06-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('car_model', models.TextField(blank=True, null=True)),
                ('car_year', models.DateField(blank=True, null=True)),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('engine_type', models.TextField(blank=True, null=True)),
                ('vin', models.TextField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('car_license_plate', models.TextField(blank=True, max_length=7, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
