# Generated by Django 3.0.7 on 2020-09-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceLiter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "engine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="about.EngineType",
                    ),
                ),
            ],
        ),
    ]
