default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  TIME_ZONE: ""

development:
  DEBUG: true
  SITE_ID: 1
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  TIME_ZONE: "Europe/Minsk"

heroku:
  ALLOWED_HOSTS:
    - .katsiaryna.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: true
  CELERY_BEAT_INVITATION: 900
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SITE_ID: 1

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"