default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SENTRY_DSN: ""

development:
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - .katsiaryna.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: true

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"