default:
  ALLOWED_HOSTS: []
  AWS_ACCESS_KEY_ID: ""
  AWS_LOCATION: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SITE_ID: 0
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  TIME_ZONE: ""

development:
  ALLOWED_HOSTS: ["ba95b199cac8.ngrok.io"]
  TG: "1157910092:AAGVTzGJA5BR94Xw0-9WtvmJFu9BQ1C_CKQ"
  AWS_LOCATION: "development"
  AWS_S3_REGION_NAME: "us-east-1"
  DEBUG: true
  SITE_ID: 1
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  TIME_ZONE: "Europe/Minsk"

docker:
  AWS_LOCATION: "docker"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_INVITATION: 30
  CELERY_BROKER_URL: "redis://my-exp-broker"
  DATABASE_URL: "postgresql://kate:123@my-exp-db:5432/my-exp"
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"

heroku:
  ALLOWED_HOSTS:
    - .katsiaryna.herokuapp.com
    - 127.0.0.1
    - localhost
  AWS_LOCATION: "heroku"
  AWS_S3_REGION_NAME: "us-east-1"
  DEBUG: true
  CELERY_BEAT_INVITATION: 900
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SITE_ID: 1

test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"